export enum error_code {
  SUCCESS = 'SUCCESS',
  USER_EXISTS = 'USER_EXIST',
  USER_NOT_EXISTS = 'USER_NOT_EXISTS',
  USER_UNACTIVE = 'USER_UNACTIVE',
  UNAUTHORIZED = 'UNAUTHORIZED',
  OTHER = 'OTHER',
}
